### ISSUE TITLE
As a developer I want to understand whether I can filter content from a mobile application in iOS so that the app's 'Zones' can function

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Beeban-5-Rights#10]

**Comment by VrushaliSJadhav** [comment]
Blocking certain websites in safari browser from an app can be achieved in iOS. 
Apple provides content blocker extension which we can add in our app.  This extension provides a way to maintain a .json file with list of URLs we want to block from loading in Safari. This can be achieved programmatically.  

Adding an extension to the app will reflect in "Content Block" setting from device's Settings:
Device Settings -> Safari -> Content Block -> App name with on/off switch. 
But this setting needs to be enabled and disabled manually by user. It can not be accessed/controlled programmatically from within the app.

**Comment by VrushaliSJadhav** [comment]
As these content blockers are part of the Mobile Safari framework,
the block list will only apply to Safari and any apps that use Safari View Controller. It will not work with any other browsers in device.
