### ISSUE TITLE
As a developer, I want to understand the related costs of using specific technology so that these can be accounted for in the budget

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Beeban-5-Rights#19]

**Comment by MoustafaBounasser** [comment]
Estimated cost of using Proxy bandwidth in AWS based on average monthly bandwidth consumption research (data/wifi) in this link
https://alm.accenture.com/wiki/display/DigitalInnovation/Beeban+5+rights+-+Solution+and+Technical+Investigation
check the matrix for key notes
