### ISSUE TITLE
As a developer, I want to understand whether I can control mobile applications (allow/restrict) in iOS so that the app's 'Zones' can function

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Beeban-5-Rights#8]

**Comment by VrushaliSJadhav** [comment]
As per Apple's guidelines we can not control or restrict other applications in device programmatically.
Apple provides a setting to restrict usage of applications but developers can not access or control that setting either.

**Comment by VrushaliSJadhav** [comment]
Every iOS app is sandboxed, which means it runs in it's own container. 
Each app has exclusive access to their own container folder and all data stored by the app is secured against read and write access of other apps.
Hence, it is impossible to access other apps data and block the app or to know when the app is launched.

Fetching other running processes from device:
iOS apps are not permitted to see what other apps are running in the device.
From iOS 9.0, apps are not privileged to see other app's information. So the certain APIs which were used earlier to fetch running processes in device, no longer work.
